module.exports = {
  devIndicators: {
    autoPrerender: false,
  },
  images: {
    domains: [
      "firebasestorage.googleapis.com",
      "cdn.cocolux.com",
      "meta.vn",
      "chiaki.vn",
      "salt.tikicdn.com",
      "product.hstatic.net",
      "cdn.tgdd.vn",
      "adminbeauty.hvnet.vn",
      "hangnhapkhauthailan.com",
      "media3.scdn.vn",
      "cf.shopee.vn",
      "www.kosmebox.com",
      "i.ebayimg.com",
      "www.watsons.vn",
      "paulaschoice.vn",
      "meihao.shopping",
      "bizweb.dktcdn.net",
      "cdn.vuahanghieu.com",
      "vn-test-11.slatic.net",
      "www.hangngoainhap.com.vn",
      "sanhangchinhhang.com",
      "ansancosmetics.com",
      "nhathuocviet.vn",
      "file.hstatic.net",
      "media.hasaki.vn",
      "ordinary.com.vn",
      "manage.kaokao.vn",
      "tudienlamdep.org",
      "skin1004.com.vn",
      "cdn.chanhtuoi.com",
      "tinvivu.com"
    ],
  },
};
